[package]
name = "cli_grader"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
tempfile = "3.20.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[dev-dependencies]
test-log = "0.2.18"

